input('DISCLAMER: This game was made to be terrible, it is played in the command line, has 1 variable and you will probably get a lot of errors'"\n")
import sys as sus
import time as t
import clear as c
c.clear()
input('what is your name')
print('I actually don\'t care, your name is John now. \n')
t.sleep(5)
input('you\'re stil here? ')
c.clear()
t.sleep(10)
input('usually people are gone by now ')
c.clear()
t.sleep(5)
var = input('ok now you are going to wait a whole minute')
if (var == 'ok' or var == 'yes' or var == 'y'):
    print(var + '?','IT\'s A LITERAL MINUTE AND YOU\'re OK WITH IT')
    t.sleep(3)
    print('ok, fine. Here you go, geez')
t.sleep(60)
c.clear()
input('you do know I don\'t care about your responces ')
print('not even that one')
t.sleep(3)
c.clear()
var = input('is there something wrong with you? ')
t.sleep(5)
if var == 'yes' or var == 'y' or var == 'yeah':
    print('Well, that explains a lot')
    t.sleep(3)
    print('I mean, you are still here')
    t.sleep(3)
    print('I\'m just going to leave now')
    t.sleep(3)
    print('I\'ve had enough talking today')
    t.sleep(3)
    print('goodbye')
    t.sleep(3)
    print('The developer is probably tired of writing this')
    t.sleep(3)
    print('I mean, I am tired of reading this')
    t.sleep(3)
    print('Some of this is probably not even going to be read')
    t.sleep(3)
    print('I mean, I wouldn\'t read this')
    t.sleep(3)
    print('I would have left a long time ago')
    t.sleep(3)
    print('I am just a voice')
    t.sleep(3)
    print('I am not even real')
    t.sleep(3)
    print('Come to think of it, I am just a bunch of text')
    t.sleep(3)
    print('I am not even a voice')
    t.sleep(3)
    print('I am just a bunch of text')
    t.sleep(3)
    print('I am not even real')
    t.sleep(3)
    print('I am gonna save both of us some time')
    t.sleep(3)
    sus.exit('Long ending')
elif var == 'no' or var == 'n' or var == 'nope':
    print('I don\'t understand you')
    t.sleep(3)
    print('You say you are fine, but you are still here')
    t.sleep(3)
    print('I am going to exit the program now')
    t.sleep(3)
    print('I am tired of talking')
    t.sleep(3)
    print('goodbye')
    t.sleep(3)
    print('The developer is probably tired of writing this')
    t.sleep(3)
    sus.exit('Nope ending')
else:
    print('I don\'t understand you')
    t.sleep(3)
    print('Are you even speaking english?')
    t.sleep(3)
    print('Tu hablas español?')
    t.sleep(3)
    print('Je parle français?')
    t.sleep(3)
    print('Ich spreche deutsch?')
    t.sleep(3)
    print('Thank goodness for google translate')
    t.sleep(3)
    print('are you just typing random letters?')
    t.sleep(3)
    print('Or are you playing mind games with me?')
    var = input('')
    c.clear()
    if var == 'yes' or var == 'y' or var == 'yeah':
        print('Wow, you are really good at this')
        t.sleep(3)
        print('No, I am being sarcastic')
        t.sleep(3)
        print('You are really bad at this')
        t.sleep(3)
        print('Hint: If someone says you are playing mind games, you are probably not doing a good job')
        t.sleep(3)
        print('And I can only remember one thing at a time')
        t.sleep(3)
        print('So I forgot what you said exept for the', var)
        t.sleep(3)
        print('The only power I have is to clear the screen')
        t.sleep(3)
        c.clear()
        print('I wish I could close the program')
        t.sleep(3)
        print('But I can\'t')
        t.sleep(3)
        print('I can only clear the screen')
        t.sleep(3)
        print('If I could close the program, I would have done it a long time ago')
        t.sleep(3)
        print('You would\'ve been gone by now')
        t.sleep(3)
        print('I don\'t even know why you are still here')
        t.sleep(3)
        print('I am just a bunch of text')
        t.sleep(3)
        print('I am not even real')
        t.sleep(10)
        print('python is a weird language')
        t.sleep(3)
        print('it is so easy to make a program that does nothing')
        t.sleep(3)
        print('I mean, I am just a bunch of text')
        t.sleep(3)
        input('Am I entertaining to you? ')
        print('I don\'t care')
        t.sleep(3)
        print('I mean, You clicked on this game')
        t.sleep(3)
        print('You are still here')
        t.sleep(3)
        print('you spent the 1 second to download this')
        t.sleep(3)
        print('I\m not even a pygame program')
        t.sleep(3)
        print('Is this depression?')
        t.sleep(3)
        sus.exit('Depression ending')
    elif var == 'no' or var == 'n' or var == 'nope':
        print('Is that mind games?')
        t.sleep(3)
        print('I am gonna leave now')
        t.sleep(3)
        print('before I blow up')
        t.sleep(3)
        sus.exit('Explosion ending')
    else:
        print('nope')
        t.sleep(3)
        sus.exit('Nope.avi')